// Copied from the Doulisha web repository by `pnpm sync:web`. Do not edit.
import { z } from 'zod';

import { localeSchema, millimesSchema, phoneInputSchema } from './common';

export const eventVisibilitySchema = z.enum(['public', 'unlisted', 'private']);
export const cancellationPolicySchema = z.enum(['flexible', 'moderate', 'strict']);
export const registrationTypeSchema = z.enum(['free_rsvp', 'paid', 'deposit', 'pay_at_door']);
export const audienceSchema = z.enum(['solo', 'couple', 'friends', 'family', 'kids']);
export const ticketKindSchema = z.enum([
  'standard',
  'early_bird',
  'vip',
  'student',
  'couple',
  'group',
]);

export const geoPointSchema = z.object({
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
});

export const eventBriefSchema = z.object({
  whatToBring: z.array(z.string().trim().min(1).max(120)).max(20).optional(),
  dressCode: z.string().trim().max(300).optional(),
  rules: z.string().trim().max(2000).optional(),
  safety: z.string().trim().max(2000).optional(),
});

/**
 * Fields the create-event wizard saves (EVT-01 to EVT-05). Every field is
 * optional so drafts can be auto-saved step by step; `publish` checks
 * completeness.
 */
export const eventPatchSchema = z.object({
  title: z.string().trim().max(120).optional(),
  description: z.string().trim().max(5000).nullish(),
  language: localeSchema.optional(),
  /** Key of the member's own `event-cover` upload; null removes the cover. */
  coverKey: z.string().max(300).nullish(),
  startsAt: z.coerce.date().optional(),
  endsAt: z.coerce.date().nullish(),
  venueName: z.string().trim().max(120).nullish(),
  address: z.string().trim().max(300).nullish(),
  city: z.string().trim().max(80).nullish(),
  location: geoPointSchema.nullish(),
  locationHiddenUntilBooking: z.boolean().optional(),
  minAge: z.number().int().min(0).max(99).nullish(),
  audience: z.array(audienceSchema).max(5).optional(),
  capacity: z.number().int().min(1).max(100_000).nullish(),
  minToConfirm: z.number().int().min(1).max(100_000).nullish(),
  waitlistEnabled: z.boolean().optional(),
  registrationType: registrationTypeSchema.optional(),
  bookingOpensAt: z.coerce.date().nullish(),
  bookingClosesAt: z.coerce.date().nullish(),
  brief: eventBriefSchema.optional(),
  cancellationPolicy: cancellationPolicySchema.optional(),
  visibility: eventVisibilitySchema.optional(),
  /** Template-specific fields; validated against the template on the server. */
  details: z.record(z.string(), z.unknown()).optional(),
  organizerProfileId: z.uuid().nullish(),
});
export type EventPatch = z.infer<typeof eventPatchSchema>;

/** TKT-02 ticket type as edited in the wizard. */
export const ticketTypeInputSchema = z.object({
  id: z.uuid().optional(),
  kind: ticketKindSchema.default('standard'),
  name: z.string().trim().min(1).max(80),
  description: z.string().trim().max(300).nullish(),
  priceMillimes: millimesSchema,
  depositMillimes: millimesSchema.nullish(),
  quantity: z.number().int().min(1).max(100_000).nullish(),
  seatsPerTicket: z.number().int().min(1).max(20).default(1),
});
export type TicketTypeInput = z.infer<typeof ticketTypeInputSchema>;

/** LOG-01 meeting point. */
export const meetingPointInputSchema = z.object({
  name: z.string().trim().min(1).max(120),
  address: z.string().trim().max(300).nullish(),
  meetAt: z.coerce.date(),
  location: geoPointSchema.nullish(),
});

/** EVT-06 programme step. */
export const programmeStepInputSchema = z.object({
  day: z.number().int().min(1).max(30).default(1),
  title: z.string().trim().min(1).max(160),
  startsAt: z.coerce.date().nullish(),
});

/** TKT-03 booking question. */
export const bookingQuestionInputSchema = z.object({
  label: z.string().trim().min(1).max(160),
  type: z.enum(['text', 'select', 'number']).default('text'),
  options: z.array(z.string().trim().min(1).max(60)).max(20).default([]),
  required: z.boolean().default(false),
});

/** A person on a booking (PRT-01). */
export const attendeeInputSchema = z.object({
  fullName: z.string().trim().min(2).max(120),
  phone: phoneInputSchema.nullish(),
  email: z.email().nullish(),
});

export const paymentChoiceSchema = z.enum(['online', 'd17', 'bank_transfer', 'cash']);

/** PAY-01 checkout request. */
export const createBookingSchema = z.object({
  eventId: z.uuid(),
  lines: z
    .array(z.object({ ticketTypeId: z.uuid(), quantity: z.number().int().min(0).max(10) }))
    .min(1)
    .max(10),
  /** The first attendee is the buyer's contact. */
  attendees: z.array(attendeeInputSchema).min(1).max(100),
  answers: z.record(z.string(), z.string().max(500)).default({}),
  meetingPointId: z.uuid().nullish(),
  payment: paymentChoiceSchema.nullish(),
  payDeposit: z.boolean().default(false),
  /** Generated by the client; a retried request returns the same order. */
  idempotencyKey: z.string().min(8).max(80),
  utm: z
    .object({
      source: z.string().max(60).optional(),
      medium: z.string().max(60).optional(),
      campaign: z.string().max(80).optional(),
      content: z.string().max(80).optional(),
    })
    .default({}),
});
export type CreateBookingInput = z.infer<typeof createBookingSchema>;

/** INV-01 quick private event. */
export const quickPrivateEventSchema = z.object({
  templateKey: z.enum(['birthday', 'private_gathering']),
  title: z.string().trim().min(3).max(120),
  startsAt: z.coerce.date(),
  venueName: z.string().trim().max(120).nullish(),
  city: z.string().trim().max(80).nullish(),
  description: z.string().trim().max(2000).nullish(),
  coverKey: z.string().max(300).nullish(),
  locationHiddenUntilBooking: z.boolean().default(false),
});

/** INV-03 RSVP. */
export const rsvpInputSchema = z.object({
  token: z.string().min(8).max(64),
  status: z.enum(['going', 'maybe', 'not_going']),
  plusOnes: z.number().int().min(0).max(10).default(0),
  dietaryNotes: z.string().trim().max(300).nullish(),
  /** Guests without an account give their name. */
  guestName: z.string().trim().min(2).max(80).nullish(),
});

/** Web links only (never `javascript:`); forms send nothing for an empty field. */
const optionalUrl = z
  .url({ protocol: /^https?$/ })
  .max(300)
  .optional();

/** ACC-03 social links: public profile addresses only (no account linking yet). */
export const socialLinksSchema = z.object({
  facebook: optionalUrl,
  instagram: optionalUrl,
  tiktok: optionalUrl,
  website: optionalUrl,
});

/** Where buyers send D17 and bank transfers (PAY-02). */
export const paymentInstructionsSchema = z.object({
  d17Number: z.string().trim().max(30).optional(),
  bankName: z.string().trim().max(80).optional(),
  rib: z
    .string()
    .trim()
    .max(40)
    .regex(/^[0-9 ]*$/, 'digits')
    .optional(),
  accountHolder: z.string().trim().max(120).optional(),
});

/** ACC-03 organizer profile. Images are upload keys, checked on the server. */
export const organizerProfileInputSchema = z.object({
  name: z.string().trim().min(2).max(80),
  bio: z.string().trim().max(1000).nullish(),
  legalStatus: z.enum(['association', 'company', 'independent']),
  categories: z.array(z.string().max(40)).max(8).default([]),
  regions: z.array(z.string().trim().max(60)).max(10).default([]),
  socialLinks: socialLinksSchema.default({}),
  contactPhone: phoneInputSchema.nullish(),
  contactEmail: z.email().nullish(),
  paymentInstructions: paymentInstructionsSchema.default({}),
  /** New logo or cover upload keys; null removes the image, undefined keeps it. */
  logoKey: z.string().max(300).nullish(),
  coverKey: z.string().max(300).nullish(),
});

/** PRT-02 attendee added by the organizer (phone or WhatsApp booking). */
export const manualAttendeeSchema = z.object({
  eventId: z.uuid(),
  ticketTypeId: z.uuid(),
  quantity: z.number().int().min(1).max(10).default(1),
  fullName: z.string().trim().min(2).max(120),
  phone: phoneInputSchema.nullish(),
  email: z.email().nullish(),
  paid: z.boolean().default(false),
  method: z.enum(['cash', 'bank_transfer', 'd17']).default('cash'),
  notes: z.string().trim().max(500).nullish(),
});

/** Password rules (ADR 0016), shared by the sign-up form and the API. */
export const passwordSchema = z.string().min(8).max(128);

/** Last step of sign-up: name, password and what the member mainly does. */
export const completeSignUpSchema = z.object({
  name: z.string().trim().min(2).max(80),
  /** Required unless the account already has a password. */
  password: passwordSchema.optional(),
  accountType: z.enum(['participant', 'organizer']),
  city: z.string().trim().max(60).nullish(),
});
